Repository heimdal/heimdal, pull requests merged in 2021-12, with the labels that each got.

#883 heimdal: Make _krb5_pac_get_kdc_checksum_info() into a global function
  lib/krb5/libkrb5-exports.def.in
  lib/krb5/pac.c
  lib/krb5/test_pac.c
  lib/krb5/version-script.map
  tests/plugin/windc.c
Labels: feature request

#878 kdc: update PAC hooks for Samba
  kdc/kdc_locl.h
  kdc/kerberos5.c
  kdc/krb5tgs.c
  kdc/windc.c
  kdc/windc_plugin.h
  tests/plugin/windc.c
Labels: feature request, bug

#884 kdc: Don't keep trying keys for encrypted-challenge
  kdc/kerberos5.c
Labels: bug
