Repository heimdal/heimdal, pull requests merged in 2022-01, with the labels that each got.

#913 kdc: return KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN (PA)
  kdc/kerberos5.c
Labels: bug

#914 gss: pass GSS_C_NO_OID name type to mechanism
  lib/gssapi/mech/gss_compare_name.c
  lib/gssapi/mech/gss_import_name.c
  lib/gssapi/sanon/import_name.c
Labels: bug

#854 hdb: Namespace referrals
  kadmin/kadmin.1
  lib/hdb/common.c
  tests/kdc/check-kdc.in
  tests/kdc/krb5.conf.in
Labels: feature request

#814 Windows 10 SDK build fixes
  appveyor.yml
  include/config.h.w32
  lib/roken/roken.h.in
  lib/roken/strtoll.c
  lib/roken/strtoull.c
  packages/windows/installer/NTMakefile
  packages/windows/installer/heimdal-installer.wxs
  windows/NTMakefile.sdk
  windows/NTMakefile.w32
Labels: buildbot, refactor

#929 kdc: move auth event definitions into KDC header
  kdc/Makefile.am
  kdc/NTMakefile
  kdc/headers.h
  kdc/kdc-audit.h
  kdc/kerberos5.c
  lib/hdb/hdb.h
Labels: refactor

#941 kdc: remove krb5_ prefix for KDC attribute functions
  kdc/altsecid_gss_preauth_authorizer.c
  kdc/kerberos5.c
  kdc/libkdc-exports.def
  kdc/process.c
  kdc/version-script.map
  tests/plugin/kdc_test_plugin.c
Labels: refactor

#934 kdc: make auditing API public
  kdc/fast.c
  kdc/kerberos5.c
  kdc/krb5tgs.c
  kdc/kx509.c
  kdc/libkdc-exports.def
  kdc/mssfu.c
  kdc/process.c
  kdc/version-script.map
Labels: refactor
